from django.utils.translation import gettext_lazy as _

STARTED = "STARTED"
PENDING = "PENDING"
COMMITTED = "COMMITTED"
INCORRECT = "INCORRECT"
REJECTED = "REJECTED"
COMPLETED = "COMPLETED"
DELIVERED = "DELIVERED"
SHIPPED = "SHIPPED"
RECEIVED = "RECEIVED"

SUCCESS = 'SUCCESS'
ACCEPTED = 'ACCEPTED'



PHYSICAL_COPY = "PHYSICAL COPY"
SCANNED_COPY = "SCANNED COPY"
DUAL_COPY = "DUAL COPY"

CRIMINAL_RECORD = "CRIMINAL RECORD"
CERTIFICATE_OF_NON_CONVICTION = "CERTIFICATE OF NON CONVICTION"

MARRIED = "MARRIED"
SINGLE = "SINGLE"
DIVORCED = "DIVORCED"
WIDOW = "WIDOW"
WIDOWER = "WIDOWER"

MALE = "M"
FEMALE = "F"
MISS = "MISS"

HIGH_INSTANCE = "CFHI"
SMALL_INSTANCE = "CFI"

SIR = 'Sir'
MRS = 'Mrs'
MS = 'Ms'

REQUEST_STATUS = (
    (STARTED, _("STARTED")),
    (PENDING, _("PENDING")),
    (COMMITTED, _("COMMITTED")),
    (REJECTED, _("REJECTED")),
    (INCORRECT, _("INCORRECT")),
    (COMPLETED, _("COMPLETED"))
)

REQUEST_FORMATS = (
    (PHYSICAL_COPY, _("PHYSICAL COPY")),
    (SCANNED_COPY, _("SCANNED COPY")),
    (DUAL_COPY, _("DUAL COPY")),
)


DELIVERY_STATUSES = (
    (STARTED, _("STARTED")),
    (SHIPPED, _("SHIPPED")),
    (RECEIVED, _("RECEIVED")),
    (DELIVERED, _("DELIVERED")),
)

TYPE_OF_DOCUMENT = (
    (CERTIFICATE_OF_NON_CONVICTION, _("CERTIFICATE OF NON CONVICTION")),
)


MARITAL_STATUS = (
    (MARRIED, _("MARRIED")),
    (SINGLE, _("SINGLE")),
    (DIVORCED, _("DIVORCED")),
    (WIDOW, _("WIDOW")),
    (WIDOWER, _("WIDOWER")),
)


GENDERS = (
    (MALE, _("M")),
    (FEMALE, _("F")),
)


COURT_TYPES = (
    (SMALL_INSTANCE, _("CFI")),
    (HIGH_INSTANCE, _("CFHI"))
)

CIVILITIES = (
    (SIR, _('Sir')),
    (MRS, _('Mrs')),
    (MS, _('Ms')),
)
