from django.utils.translation import gettext_lazy as _

STARTED = "STARTED"
PENDING = "PENDING"
COMPLETED = "COMPLETED"
DELIVERED = "DELIVERED"

PHYSICAL_COPY = "PHYSICAL COPY"
SCANNED_COPY = "SCANNED COPY"
DUAL_COPY = "DUAL COPY"

CRIMINAL_RECORD = "CRIMINAL RECORD"
CERTIFICATE_OF_NON_CONVICTION = "CERTIFICATE OF NON CONVICTION"

MARRIED = "MARRIED"
SINGLE = "SINGLE"
DIVORCED = "DIVORCED"

MALE = "M"
FEMALE = "F"
MISS = "MISS"

HIGH_INSTANCE = "HIGH INSTANCE"
SMALL_INSTANCE = "SMALL INSTANCE"

REQUEST_STATUS = (
    (STARTED, _("STARTED")),
    (PENDING, _("PENDING")),
    (COMPLETED, _("COMPLETED"))
)

REQUEST_FORMATS = (
    (PHYSICAL_COPY, _("PHYSICAL COPY")),
    (SCANNED_COPY, _("SCANNED COPY")),
    (DUAL_COPY, _("DUAL COPY")),
)


SHIPMENT_STATUS = (
    (STARTED, _("STARTED")),
    (PENDING, _("PENDING")),
    (DELIVERED, _("DELIVERED")),
)

TYPE_OF_DOCUMENT = (
    (CRIMINAL_RECORD, _("CRIMINAL RECORD")),
    (CERTIFICATE_OF_NON_CONVICTION, _("CERTIFICATE OF NON CONVICTION")),
)


MARITAL_STATUS = (
    (MARRIED, _("MARRIED")),
    (SINGLE, _("SINGLE")),
    (DIVORCED, _("DIVORCED")),
)


GENDERS = (
    (MALE, _("M")),
    (FEMALE, _("F")),
)


COURT_TYPES = (
    (SMALL_INSTANCE, _("SMALL INSTANCE")),
    (HIGH_INSTANCE, _("HIGH INSTANCE"))
)
