# Stage 1: Build the Vue.js application
FROM node:lts-alpine as builder
WORKDIR /app
COPY web/package*.json ./
RUN npm install
COPY ./web/ .
RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]