# Generated by Django 5.0.1 on 2024-01-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True),
        ),
    ]
