# Generated by Django 5.0.4 on 2025-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('iso2', 'lang'), ('iso3', 'lang'), ('name', 'lang')},
        ),
    ]
