# Generated by Django 5.0.1 on 2024-01-20 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_court_slug_alter_department_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('iso2', models.CharField(db_index=True, max_length=2, unique=True)),
                ('iso3', models.CharField(db_index=True, max_length=3, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='code',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_cob',
            field=models.ForeignKey(blank=True, help_text='Country of birth', max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.country'),
        ),
    ]
