# Generated by Django 5.0.1 on 2024-01-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_court_municipality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user_pob',
            new_name='user_mob',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='destination',
        ),
        migrations.AddField(
            model_name='agent',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='pending_task_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='amount',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Amount of the request'),
        ),
        migrations.AddField(
            model_name='request',
            name='purpose',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Describe the purpose of your request'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_residency_hood',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name="Residency's hood"),
        ),
        migrations.AddField(
            model_name='request',
            name='user_residency_municipality',
            field=models.ForeignKey(blank=True, help_text='Municipality of residency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_residency_municipality', to='request.municipality'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_residency_town',
            field=models.ForeignKey(blank=True, help_text='Town of residency', max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.town'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='request.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_hood',
            field=models.CharField(blank=True, db_index=True, help_text='Hood where a requested document will be shipped', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_municipality',
            field=models.ForeignKey(blank=True, help_text='Municipality where a requested document will be shipped', null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.municipality'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_town',
            field=models.ForeignKey(blank=True, help_text='Town where a requested document will be shipped', null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.town'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED')], db_index=True, default='STARTED', max_length=150),
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='court',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='request.court'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], db_index=True, default='STARTED', max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_cob',
            field=models.ForeignKey(blank=True, help_text='Country of birth', max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cob', to='request.country'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_nationality',
            field=models.ForeignKey(blank=True, help_text='Nationality of client requesting the service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_nationality', to='request.country'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_residency_country',
            field=models.ForeignKey(default=None, help_text='Country of residency', on_delete=django.db.models.deletion.PROTECT, related_name='user_residency_country', to='request.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='request.request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='transport_company',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
