# Generated by Django 5.0.1 on 2024-01-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_rename_user_pob_request_user_mob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
