# Generated by Django 5.0.1 on 2024-01-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_country_alter_request_code_alter_request_user_cob'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user_birthday_certificate',
            field=models.FileField(blank=True, db_index=True, help_text='Birthday certificate of client requesting the service', null=True, upload_to='SCANS'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_passport',
            field=models.FileField(blank=True, db_index=True, help_text='Passport of client requesting the service', null=True, upload_to='SCANS'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_email',
            field=models.EmailField(db_index=True, help_text='Email of client requesting the service', max_length=150),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id_scan',
            field=models.FileField(blank=True, db_index=True, help_text='ID card scan of client requesting the service', null=True, upload_to='SCANS'),
        ),
    ]
