# Generated by Django 5.0.1 on 2024-01-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_country_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(db_index=True, default='contact@africadigitalxperts.com', max_length=254),
            preserve_default=False,
        ),
    ]
