# Generated by Django 5.0.4 on 2025-03-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_region_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('format', 'ror_code', 'rob_code', 'cor_code')},
        ),
    ]
