# Generated by Django 5.0.1 on 2024-01-24 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_alter_court_unique_together_municipality_court_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='court',
        ),
        migrations.AddField(
            model_name='department',
            name='court',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.court'),
        ),
    ]
