# Generated by Django 5.0.1 on 2024-01-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_remove_municipality_court_department_court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='region',
        ),
        migrations.RemoveField(
            model_name='department',
            name='court',
        ),
        migrations.AddField(
            model_name='court',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.department'),
        ),
    ]
