# Generated by Django 5.0.1 on 2024-01-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_remove_court_region_remove_department_court_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
