# Generated by Django 5.0.1 on 2024-01-25 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_alter_agent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='currency_code',
            field=models.CharField(default='XAF', help_text='Code of your currency. Eg: <strong>USD, GBP, EUR, XAF,</strong> ...', max_length=5),
        ),
        migrations.AlterField(
            model_name='request',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.service'),
        ),
    ]
