# Generated by Django 5.0.1 on 2024-01-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_service_currency_code_alter_request_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user_gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], db_index=True, help_text='Gender of client requesting the service', max_length=6),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_last_name',
            field=models.CharField(blank=True, db_index=True, help_text='Last name of the client requesting the service', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_phone_number_2',
            field=models.CharField(blank=True, db_index=True, help_text='2nd phone number of the client  of client requesting the service', max_length=15, null=True),
        ),
    ]
