# Generated by Django 5.0.1 on 2024-01-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_alter_request_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user_last_name',
            field=models.CharField(db_index=True, default=0, help_text='Last name of the client requesting the service', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='user_middle_name',
            field=models.CharField(blank=True, db_index=True, help_text='Middle name of client requesting the service', max_length=150, null=True),
        ),
    ]
