# Generated by Django 5.0.1 on 2024-01-25 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_remove_request_user_mob_request_user_dpb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='code',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_cob',
            field=models.ForeignKey(blank=True, help_text='Country of birth', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cob', to='request.country'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_dpb',
            field=models.ForeignKey(blank=True, help_text='Department of birth', null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.department'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_residency_town',
            field=models.ForeignKey(blank=True, help_text='Town of residency', null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.town'),
        ),
    ]
