# Generated by Django 5.0.1 on 2024-01-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_alter_request_code_alter_request_user_cob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
