# Generated by Django 5.0.1 on 2024-01-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_alter_request_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cob',
            field=models.ForeignKey(blank=True, help_text='Country of birth', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cob', to='request.country'),
        ),
    ]
