# Generated by Django 5.0.1 on 2024-02-01 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_alter_request_user_cob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user_id_scan',
            new_name='user_id_scan_1',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='user_passport',
            new_name='user_passport_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cob',
        ),
        migrations.AddField(
            model_name='request',
            name='user_address',
            field=models.CharField(blank=True, help_text='Address line where the user stays', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='user_id_scan_2',
            field=models.FileField(blank=True, db_index=True, help_text='ID card scan of client requesting the service', null=True, upload_to='SCANS'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_passport_2',
            field=models.FileField(blank=True, db_index=True, help_text='Passport of client requesting the service', null=True, upload_to='SCANS'),
        ),
        migrations.AddField(
            model_name='service',
            name='cor',
            field=models.ForeignKey(blank=True, help_text='Country of residency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cor', to='request.country'),
        ),
    ]
