# Generated by Django 5.0.1 on 2024-02-01 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_rename_user_id_scan_request_user_id_scan_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user_email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email of client requesting the service', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_residency_country',
            field=models.ForeignKey(blank=True, help_text='Country of residency', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_residency_country', to='request.country'),
        ),
    ]
