# Generated by Django 5.0.1 on 2024-02-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0019_alter_request_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='proof_of_stay',
            field=models.FileField(blank=True, db_index=True, help_text='Proof of stay in Cameroon', null=True, upload_to='SCANS'),
        ),
    ]
