# Generated by Django 5.0.1 on 2024-02-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0021_request_user_close_friend_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='civility',
            field=models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle')], db_index=True, default='', help_text='Civility of the client requesting the service', max_length=15),
        ),
        migrations.AddField(
            model_name='request',
            name='user_full_name',
            field=models.CharField(db_index=True, default='Monsieur', help_text='Full name of the client requesting the service', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.CharField(choices=[('TPI', 'TPI'), ('TPGI', 'TPGI')], db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_of_document',
            field=models.CharField(choices=[('EXTRAIT DE CASIER JUDICIAIRE', 'EXTRAIT DE CASIER JUDICIAIRE'), ('CERTIFICATE OF NON CONVICTION', 'CERTIFICATE OF NON CONVICTION')], max_length=150),
        ),
    ]
