# Generated by Django 5.0.1 on 2024-02-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0022_request_civility_request_user_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='civility',
        ),
        migrations.AddField(
            model_name='request',
            name='user_civility',
            field=models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle')], db_index=True, default='', help_text='Civility of the client requesting the service', max_length=15, verbose_name='Civility'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_postal_code',
            field=models.CharField(blank=True, help_text="Postal address of the client, it's going to be use to ship request", max_length=150, null=True, verbose_name='Postal code'),
        ),
    ]
