# Generated by Django 5.0.1 on 2024-02-04 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0023_remove_request_civility_request_user_civility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user_cob',
            field=models.ForeignKey(blank=True, default=None, help_text='Country of birth', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cob', to='request.country'),
        ),
    ]
