# Generated by Django 5.0.1 on 2024-02-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0024_alter_request_user_cob'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user_birthday_certificate_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='user_id_card_1_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='user_id_card_2_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='user_passport_1_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='user_passport_2_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='user_proof_of_stay_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='user_wedding_certificate_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
