# Generated by Django 5.0.1 on 2024-02-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0025_request_user_birthday_certificate_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('format', 'ror', 'rob'), ('rob', 'cor'), ('ror', 'rob')},
        ),
    ]
