# Generated by Django 5.0.1 on 2024-02-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0026_alter_service_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('format', 'rob', 'cor'), ('format', 'ror', 'rob')},
        ),
    ]
