# Generated by Django 5.0.1 on 2024-02-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0027_alter_service_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.court'),
        ),
    ]
