# Generated by Django 5.0.1 on 2024-02-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0031_payment_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='request_code',
            field=models.CharField(db_index=True, max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_last_name',
            field=models.CharField(blank=True, db_index=True, help_text='Last name of the client requesting the service', max_length=150, null=True),
        ),
    ]
