# Generated by Django 5.0.1 on 2024-02-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0032_alter_payment_request_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='request_code',
            field=models.CharField(db_index=True, max_length=24, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('request_code', 'status')},
        ),
    ]
