# Generated by Django 5.0.1 on 2024-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0034_payment_mean_shipment_destination_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='destination_address',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='request',
            name='destination_location',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
