# Generated by Django 5.0.1 on 2024-02-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0035_request_destination_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.agent'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('PENDING', 'PENDING'), ('COMMITTED', 'COMMITTED'), ('REJECTED', 'REJECTED'), ('INCORRECT', 'INCORRECT'), ('COMPLETED', 'COMPLETED')], db_index=True, default='STARTED', max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_marital_status',
            field=models.CharField(blank=True, choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE'), ('DIVORCED', 'DIVORCED'), ('WIDOW', 'WIDOW'), ('WIDOWER', 'WIDOWER')], db_index=True, max_length=150, null=True, verbose_name='Marital status of the client requesting the service'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('SHIPPED', 'SHIPPED'), ('RECEIVED', 'RECEIVED'), ('DELIVERED', 'DELIVERED')], db_index=True, default='STARTED', max_length=150),
        ),
    ]
