# Generated by Django 5.0.1 on 2024-02-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0038_alter_payment_status_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=36, unique=True),
        ),
    ]
