# Generated by Django 5.0.1 on 2024-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0041_service_dispursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.CharField(default='', help_text='Message rendered by the gateway for initiated payment transaction ...', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
