# Generated by Django 5.0.1 on 2024-03-28 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0044_alter_agent_managers_remove_service_dispursement_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agent',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
