# Generated by Django 5.0.1 on 2024-03-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0045_alter_agent_managers_alter_agent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='password',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='username',
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='first_name',
            field=models.CharField(db_index=True, help_text='First name of the client requesting the service', max_length=150),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, help_text='Last name of the client requesting the service', max_length=150, null=True),
        ),
    ]
