# Generated by Django 5.0.1 on 2024-03-31 12:44

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0047_agent_date_joined_agent_groups_agent_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agent',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
