# Generated by Django 5.0.1 on 2024-03-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0050_alter_agent_managers_alter_agent_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.region'),
        ),
    ]
