# Generated by Django 5.0.1 on 2024-03-31 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0052_alter_agent_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('view_user_birthday_certificate', 'Can view and download birthday certificate'), ('view_user_passport', 'Can view and download birthday certificate'), ('view_proof_of_stay', 'Can view and download birthday certificate'), ('view_id_card', 'Can view and download birthday certificate'), ('view_wedding_certificate', 'Can view and download birthday certificate'), ('view_destination_address', 'Can view and download birthday certificate'), ('view_destination_location', 'Can view attachment details'), ('change_request_status', 'Can change status of a request')]},
        ),
    ]
