# Generated by Django 5.0.1 on 2024-04-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0053_alter_agent_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agent',
            managers=[
            ],
        ),
    ]
