# Generated by Django 5.0.1 on 2024-04-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0054_alter_agent_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company ...', max_length=255)),
                ('percentage', models.PositiveIntegerField(default=0, help_text='Percentage the company earns for disbursement on each transaction. Eg: 5')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='disbursement',
        ),
        migrations.AddField(
            model_name='service',
            name='honorary',
            field=models.PositiveIntegerField(default=2500, verbose_name='Honorary fee of the service'),
        ),
        migrations.AddField(
            model_name='service',
            name='stamp_fee',
            field=models.PositiveIntegerField(default=3100, verbose_name='Recognized stamp fee of the service'),
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.company')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.payment')),
            ],
        ),
    ]
