# Generated by Django 5.0.1 on 2024-04-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0055_company_remove_service_disbursement_service_honorary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='honorary',
        ),
        migrations.AddField(
            model_name='service',
            name='disbursement',
            field=models.FloatField(default=0, verbose_name='Disbursement fee of the service'),
        ),
        migrations.AddField(
            model_name='service',
            name='honorary_fee',
            field=models.FloatField(default=0, verbose_name='Honorary fee of the service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='stamp_fee',
            field=models.FloatField(default=0, verbose_name='Recognized stamp fee of the service'),
        ),
    ]
