# Generated by Django 5.0.1 on 2024-04-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0056_remove_service_honorary_service_disbursement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='percentage',
            field=models.PositiveIntegerField(default=0, help_text='Percentage the company earns for disbursement on each transaction. Eg: 5, 3, 25 etc...'),
        ),
    ]
