# Generated by Django 5.0.1 on 2024-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0057_disbursement_created_on_disbursement_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
