# Generated by Django 5.0.1 on 2024-04-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0058_disbursement_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
