# Generated by Django 5.0.1 on 2024-04-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0060_alter_agent_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_csa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='additional_cr_fee',
            field=models.FloatField(default=0, verbose_name='Default additional criminal record fee of the service'),
        ),
    ]
