# Generated by Django 5.0.1 on 2024-04-11 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0061_agent_is_csa_service_additional_cr_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.court'),
        ),
    ]
