# Generated by Django 5.0.1 on 2024-05-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0062_alter_agent_court'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_fee', models.FloatField(db_index=True)),
                ('stamp_quantity', models.IntegerField(db_index=True)),
                ('honorary_fee', models.FloatField(db_index=True)),
                ('honorary_quantity', models.IntegerField(db_index=True)),
                ('disbursement_fee', models.FloatField(db_index=True)),
                ('disbursement_quantity', models.CharField(default='Forfait', max_length=150)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='request.request')),
            ],
        ),
    ]
