# Generated by Django 5.0.4 on 2024-06-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0062_alter_agent_court'),
    ]

    operations = [
       # migrations.AddField(
       #     model_name='service',
       #     name='excavation_fee',
       #     field=models.FloatField(default=500, verbose_name='Excavation fee of the service'),
       # ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_fee', models.FloatField(db_index=True)),
                ('stamp_quantity', models.IntegerField(db_index=True)),
                ('honorary_fee', models.FloatField(db_index=True)),
                ('honorary_quantity', models.IntegerField(db_index=True)),
                ('disbursement_fee', models.FloatField(db_index=True)),
                ('disbursement_quantity', models.CharField(default='Forfait', max_length=150)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='request.request')),
            ],
        ),
    ]
