# Generated by Django 5.0.4 on 2024-06-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0063_service_excavation_fee_expensereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='excavation_fee',
            field=models.FloatField(default=500, verbose_name='Excavation fee of the service'),
        ),
    ]
